/* eslint */

'use strict';

module.exports = {
  dist: './_dist',
  libdir: './lib',
  libname: 'PicoQ',
  parent: 'this',
  noparent: '-noparent',
  index: './index.js',
  // These are the Javascript files required to build the library.
  src: {
    standard: [
      './src/_header',
      './src/tree.js',
      './src/picoq.js',
      './src/utils/_.js',
      './src/utils/utilities.js',
      './src/methods/select.js',
      './src/methods/dom.js',
      './src/methods/css.js',
      './src/methods/class.js',
      './src/methods/attr.js',
      './src/methods/events.js',
      './src/methods/animate.js',
      './src/ajax/ajaxprivate.js',
      './src/ajax/ajaxstatic.js',
      './src/ajax/ajaxmethods.js',
      './src/_footer',
    ],
    easing: [
      './src/_header',
      './src/tree.js',
      './src/picoq.js',
      './src/utils/_.js',
      './src/utils/utilities.js',
      './src/methods/select.js',
      './src/methods/dom.js',
      './src/methods/css.js',
      './src/methods/class.js',
      './src/methods/attr.js',
      './src/methods/events.js',
      './src/methods/easing.js',
      './src/methods/animate.js',
      './src/ajax/ajaxprivate.js',
      './src/ajax/ajaxstatic.js',
      './src/ajax/ajaxmethods.js',
      './src/_footer',
    ],
  },
  license: {
    standard: ['/*! ****************************************************************************',
      ' * {{lib:name}} v{{lib:version}}',
      ' *',
      ' * {{lib:description}}.',
      ' * (you can download it from npm or github repositories)',
      ' * Copyright (c) 2019 {{lib:author}} <{{lib:email}}> ({{lib:url}}).',
      ' * Released under the MIT license. You may obtain a copy of the License',
      ' * at: http://www.opensource.org/licenses/mit-license.php).',
      ' * ************************************************************************** */',
      ''].join('\n'),
    easing: ['/*! ****************************************************************************',
      ' * {{lib:name}} v{{lib:version}}',
      ' *',
      ' * {{lib:description}}.',
      ' * (you can download it from npm or github repositories)',
      ' * Copyright (c) 2019 {{lib:author}} <{{lib:email}}> ({{lib:url}}).',
      ' * Released under the MIT license. You may obtain a copy of the License',
      ' * at: http://www.opensource.org/licenses/mit-license.php).',
      ' *',
      ' * {{lib:name}}-easing includes portions of code for easing equations.',
      ' * Open source under the BSD License.',
      ' * Copyright (c) 2001 Robert Penner',
      ' * ************************************************************************** */',
      ''].join('\n'),
  },
};
