/* eslint */

'use strict';

module.exports = {
  dist: './_dist',
  libdir: './lib',
  libname: 'PicoQ',
  parent: 'this',
  noparent: '-noparent',
  index: './index.js',
  // These are the Javascript files required to build the library.
  src: {
    standard: [
      './src/_header',
      './src/picoQ.js',
      './src/lib/extend.js',
      './src/lib/utilities.js',
      './src/lib/select.js',
      './src/lib/dom.js',
      './src/lib/css.js',
      './src/lib/class.js',
      './src/lib/attr.js',
      './src/lib/events.js',
      './src/lib/animate.js',
      './src/lib/ajax.js',
      './src/_footer',
    ],
    easing: [
      './src/_header',
      './src/picoQ.js',
      './src/lib/extend.js',
      './src/lib/utilities.js',
      './src/lib/select.js',
      './src/lib/dom.js',
      './src/lib/css.js',
      './src/lib/class.js',
      './src/lib/attr.js',
      './src/lib/events.js',
      './src/lib/easing.js',
      './src/lib/animate.js',
      './src/lib/ajax.js',
      './src/_footer',
    ],
  },
  license: {
    standard: ['/*! ****************************************************************************',
      ' * {{lib:name}} v{{lib:version}}',
      ' *',
      ' * {{lib:description}}.',
      ' * (you can download it from npm or github repositories)',
      ' * Copyright (c) 2019 {{lib:author}} <{{lib:email}}> ({{lib:url}}).',
      ' * Released under the MIT license. You may obtain a copy of the License',
      ' * at: http://www.opensource.org/licenses/mit-license.php).',
      ' * ************************************************************************** */',
      ''].join('\n'),
    easing: ['/*! ****************************************************************************',
      ' * {{lib:name}} v{{lib:version}}',
      ' *',
      ' * {{lib:description}}.',
      ' * (you can download it from npm or github repositories)',
      ' * Copyright (c) 2019 {{lib:author}} <{{lib:email}}> ({{lib:url}}).',
      ' * Released under the MIT license. You may obtain a copy of the License',
      ' * at: http://www.opensource.org/licenses/mit-license.php).',
      ' *',
      ' * {{lib:name}}-easing includes portions of code for easing equations.',
      ' * Open source under the BSD License.',
      ' * Copyright (c) 2001 Robert Penner',
      ' * ************************************************************************** */',
      ''].join('\n'),
  },
};
